export const TABLE_RESIZE = 'TABLE_RESIZE';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_CELL_STYLES = 'CHANGE_CELL_STYLES';
export const SET_TOOLBAR_STYLES = 'SET_TOOLBAR_STYLES';
